package com.qf.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Emp implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMP.EMPNO
     *
     * @mbggenerated
     */
    private Short empno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMP.ENAME
     *
     * @mbggenerated
     */
    private String ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMP.JOB
     *
     * @mbggenerated
     */
    private String job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMP.MGR
     *
     * @mbggenerated
     */
    private Short mgr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMP.HIREDATE
     *
     * @mbggenerated
     */
    private Date hiredate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMP.SAL
     *
     * @mbggenerated
     */
    private BigDecimal sal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMP.COMM
     *
     * @mbggenerated
     */
    private BigDecimal comm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMP.DEPTNO
     *
     * @mbggenerated
     */
    private Short deptno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table EMP
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP.EMPNO
     *
     * @return the value of EMP.EMPNO
     *
     * @mbggenerated
     */
    public Short getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP.EMPNO
     *
     * @param empno the value for EMP.EMPNO
     *
     * @mbggenerated
     */
    public void setEmpno(Short empno) {
        this.empno = empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP.ENAME
     *
     * @return the value of EMP.ENAME
     *
     * @mbggenerated
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP.ENAME
     *
     * @param ename the value for EMP.ENAME
     *
     * @mbggenerated
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP.JOB
     *
     * @return the value of EMP.JOB
     *
     * @mbggenerated
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP.JOB
     *
     * @param job the value for EMP.JOB
     *
     * @mbggenerated
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP.MGR
     *
     * @return the value of EMP.MGR
     *
     * @mbggenerated
     */
    public Short getMgr() {
        return mgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP.MGR
     *
     * @param mgr the value for EMP.MGR
     *
     * @mbggenerated
     */
    public void setMgr(Short mgr) {
        this.mgr = mgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP.HIREDATE
     *
     * @return the value of EMP.HIREDATE
     *
     * @mbggenerated
     */
    public Date getHiredate() {
        return hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP.HIREDATE
     *
     * @param hiredate the value for EMP.HIREDATE
     *
     * @mbggenerated
     */
    public void setHiredate(Date hiredate) {
        this.hiredate = hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP.SAL
     *
     * @return the value of EMP.SAL
     *
     * @mbggenerated
     */
    public BigDecimal getSal() {
        return sal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP.SAL
     *
     * @param sal the value for EMP.SAL
     *
     * @mbggenerated
     */
    public void setSal(BigDecimal sal) {
        this.sal = sal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP.COMM
     *
     * @return the value of EMP.COMM
     *
     * @mbggenerated
     */
    public BigDecimal getComm() {
        return comm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP.COMM
     *
     * @param comm the value for EMP.COMM
     *
     * @mbggenerated
     */
    public void setComm(BigDecimal comm) {
        this.comm = comm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP.DEPTNO
     *
     * @return the value of EMP.DEPTNO
     *
     * @mbggenerated
     */
    public Short getDeptno() {
        return deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP.DEPTNO
     *
     * @param deptno the value for EMP.DEPTNO
     *
     * @mbggenerated
     */
    public void setDeptno(Short deptno) {
        this.deptno = deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMP
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", empno=").append(empno);
        sb.append(", ename=").append(ename);
        sb.append(", job=").append(job);
        sb.append(", mgr=").append(mgr);
        sb.append(", hiredate=").append(hiredate);
        sb.append(", sal=").append(sal);
        sb.append(", comm=").append(comm);
        sb.append(", deptno=").append(deptno);
        sb.append("]");
        return sb.toString();
    }
}